# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SDL2.OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDL2.OC
  pod 'SDL2', :path => '../../', :inhibit_warnings => true

end
