# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SDL2.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDL2.Swift
  
#  pod 'SDL2/SDL', :path => '../'
#  pod 'SDL2/SDL2', :path => '../'
  pod 'SDL2', :path => '../'

end
